### ISSUE TITLE
meta armure

### ISSUE THREAD

**Issue by Sphins** [DjLeChuck/foundryvtt-knight-compendium#1]
bon je suis pas sur que tous te concerne (a mon avis une partie va retourner auprès de zakarik

- sur la Priest les évolutions sont impossible j ai un message d'erreur 
![Capture](https://user-images.githubusercontent.com/90192087/197718029-0e4c0a24-dbf0-4e47-9dbc-fd9e6788c5e7.PNG)

- sur la ranger aucune des évolution ne semble être enregistrer (vérifier l api surement)

- sur la monk il est impossible de modifier les effets lier a l evolution 250pg
L’effet [parasitage 2](https://www.knight-jdr-systeme.fr/effect/parasitage-x/) de la vague d’énergie devient l’effet [parasitage 4](https://www.knight-jdr-systeme.fr/effect/parasitage-x/).
L’effet [dispersion 3](https://www.knight-jdr-systeme.fr/effect/dispersion-x/) de la salve d’énergie devient l’effet [dispersion 6](https://www.knight-jdr-systeme.fr/effect/dispersion-x/).
L’effet [perce armure 40](https://www.knight-jdr-systeme.fr/effect/perce-armure-x/) du rayon d’énergie devient l’effet [ignore armure](https://www.knight-jdr-systeme.fr/effect/ignore-armure/).

![Capture](https://user-images.githubusercontent.com/90192087/197719908-ec82556f-83a2-4b42-9bd6-8123047d04c4.PNG)

-Druide: les capacité ne sont pas présente dans la fiche du compendium (mode Companion) 

d'ailleurs je sais pas si ces possible de ton coté ou si on devras le faire en manuel mais a l activation des diffèrent mode des fiches de perso son créée pour le lions ou les loups ou les corbeau et ces fiche sont vide (a voir si possible de compléter via l api)

- et enfin aucune des évolution n'est pris en comte on écrase pas les donnée de base.

**Comment by DjLeChuck** [comment]
* Ranger - En effet, pas d'évolution dans l'API, et cette note le confirme : `Cette armure n'a pas d'évolutions automatiques mais peut acheter des améliorations spéciales pour son arme.`. Il faudrait donc peut-être voir avec Zakarik si c'est géré par le système nativement ou si on prépare quelque chose dans les compendiums.
* Monk - Possible que ça soit pour Zakarik
* Pour le dernier point oui c'est normal, l'API ne donne pas ses infos. Comme je disais su rle Discord à qqn d'autre ce matin : Il va falloir ajuster manuellement pas mal de choses sur les compendiums et ça en fait parti 😄

**Comment by Sphins** [comment]
-du coup la ranger et la druide  on les fera a la main tous est prévus par zakarik et je fait le report pour la monk meme si j ai pas encore verifier ce point la pour toute les armures

**Comment by DjLeChuck** [comment]
En disant `Pour le dernier point`, je parlais de `et enfin aucune des évolution n'est pris en comte on écrase pas les donnée de base.

Pour la Druide je n'ai pas regardé si c'était normal ou pas ! 😄
