### ISSUE TITLE
problêmes sur la berserk

### ISSUE THREAD

**Issue by Mnemomos** [DjLeChuck/foundryvtt-knight-compendium#13]
Bonjour, voici la liste des problêmes qu'on a avec la berserk :

le bonus d'égide est à 0 et pas a 6
![image](https://user-images.githubusercontent.com/92275753/202717496-b44ca248-79aa-40c7-9cca-da9fb139170f.png)

Les Lvl Up semblent ne pas marcher : 
- Le nombre de paliers d'évolution n'augmente jamais
- le nombre de points d'espoir donnés par l'armure ne change jamais

Sachant que quand j'essaye de changer le nombre de paliers d'évolutions, la fiche se mets a mal marchée.

Merci et bonne journée

**Comment by DjLeChuck** [comment]
Souci d'égide corrigé pour la prochaine version

**Comment by DjLeChuck** [comment]
Tout est corrigé pour la prochaine version
