### ISSUE TITLE
Ajouts au compendium

### ISSUE THREAD

**Issue by Mnemomos** [DjLeChuck/foundryvtt-knight-compendium#14]
Bonjour
Dans les choses qui nous en semblées manquer dans le compendium :
les modifications liées au cristal d'abysse (perte d'espoir, gain d'énergie et de cdf)
     les améliorations du cristal 
Les gain à chaque morceau du graal trouvé (espoir et égide)

Passage à la lamasserie (+5pv+5Espoir)
Motivation majeure réussie (+25espoir)

Distinctions (présente 67 de l'atlas)

Personellement je les ai créer via des avantages/inconvenients et des modules pour le cristal d'abysse. Je ne sait pas si il y aurait une autre façon de le faire.
![image](https://user-images.githubusercontent.com/92275753/202719581-bda0bcf2-2f54-43f7-b786-660198d61b37.png)

Bonne journée

**Comment by DjLeChuck** [comment]
Je viens de discuter de tout cela avec Zakarik et pour lui ce sont des choses qui finiront par arriver dans le système à un moment ou un autre.
Du coup je préfère ne rien ajouter dans le module car c'est trop "bancal" comme façon de faire, même si "ça marche".
