### ISSUE TITLE
montée de niveau de module

### ISSUE THREAD

**Issue by Mnemomos** [DjLeChuck/foundryvtt-knight-compendium#15]
Bonjour
C'est plus un questionnement qu'une issue,  actuellement, si on veut avoir un module lvl 2, il faut avoir le niveau 1 et le niveau 2
comme ceci :
![image](https://user-images.githubusercontent.com/92275753/202720429-5ad30a2b-ce1f-4c2f-a473-acdb33711861.png)

J'ai l'impression qu'il serait meilleur d'augmenter le cout en PG des niveaux supérieurs (pour que le saut 2 coute le prix du saut 1+du saut 2) et ainsi supprimer le saut 1 quand on veut s'équiper du saut 2.
En faisant ainsi, on aurait une fiche plus clair et plus efficace.

![image](https://user-images.githubusercontent.com/92275753/202720800-375e1cb6-7a0a-4bbd-b983-c9159ef04a65.png)

Pour l'instant, la solution que nous utilisont a notre table c'est de s'équiper uniquement de la version la plus récente et de modifier la liste des dépenses pour rajouter la version précédente mais c'est pas trés propre.

Voila, je ne sait pas si il y a une raison technique pour laquelle les choses sont faites comme ça pour l'instant, si c'est pour garder le même modêle que pour les OD (ou l'utilitée est réelle) ou autre.

Merci encore et bonne journée!

**Comment by DjLeChuck** [comment]
Corrigé sur la prochaine version
