### ISSUE TITLE
Erreur sur l'évolution de la Warmaster

### ISSUE THREAD

**Issue by Zakarik** [DjLeChuck/foundryvtt-knight-compendium#16]
Ca vaut pour toutes les armures, si concernant les évolutions des capacités, ça remplace (donc toujours prendre en compte les évolutions précédentes), pour ce qui est des évolutions bonus d'armure, de champs de force, du bonus d'énergie ou du bonus d'espoir, ça ne remplace pas, ça s'ajoute, donc :

Le bonus d'énergie dans les évolutions devrait être :
- 150 PG : 10
- 200 PG : 0
- 250 PG : 10

**Comment by DjLeChuck** [comment]
Corrigé dans la prochaine version
