### ISSUE TITLE
Affectation des images pour les ennemis du nodachi

### ISSUE THREAD

**Issue by Tenariel** [DjLeChuck/foundryvtt-knight-compendium#19]
Bonjour,

J'ai remarqué qu'il manquait des images pour les ennemis du nodachi alors qu'on a des images officiels dans les documents livre de base et supplément nodachi. Je me permet donc de préciser ici les pages que j'ai trouvé pour ces ennemis:

 On a une image du meta soldat dans le supplément nodachi  page 53,
Cyber ninja livre de base page 405, Samourai livre de base p 238, shinobi (ou ninja) supplément nodachi page 55. Seule le yojimbo n'a pas d'image (enfin j'en ai pas trouvé).

Cdt,

Tenariel

**Comment by DjLeChuck** [comment]
Bonjour,

J'ai justement ajouté les images il y a 1h ! https://github.com/DjLeChuck/foundryvtt-knight-compendium/commit/ea01d88305f5227a940271978c9f767d960d1fab

Elles seront donc dans la prochaine version du module que je ferais dans le WE. :)
