### ISSUE TITLE
[Suggestion] Ajout des modules "de base" d'une méta-armure.

### ISSUE THREAD

**Issue by Angor-de-Redjak** [DjLeChuck/foundryvtt-knight-compendium#20]
Pages 132/133 du livre de base

Il y a une liste de modules de base présents dans toutes les armures.
Certains éléments peuvent paraître anecdotiques (module fold ou rack, par exemple) mais certains ont des intérêts non-négligeables qu'on a tendance à oublier en partie (module lampes UV qui applique l'effet lumière 1).

Est-ce qu'il ne serait pas envisageable de les intégrer au compendium ?
Quitte à faire un seul et unique objet "module de base" contenant tout le listing, sauf peut-être ceux qui appliquent des effets ou des stats particulières ?

Voilà, c'est une petite proposition !

**Comment by DjLeChuck** [comment]
Fixed via 224f8948a9726d9968ed0aa7d8eda8ab5fa7b1ca
