### ISSUE TITLE
[Suggestion] QOL Warrior

### ISSUE THREAD

**Issue by Angor-de-Redjak** [DjLeChuck/foundryvtt-knight-compendium#21]
Est-ce que ça ne vaudrait pas le coup (pour les fins de soirées où tout le monde est fatigué, par exemple) de rajouter dans la description de la Warrior à quel aspect correspond chaque Type ?

**Comment by DjLeChuck** [comment]
Fixed via 6d60d8e3940d5f1a64d3759d51dec23e4cbfe9ee
