### ISSUE TITLE
Améliorations impossible sur le Longbow du Ranger

### ISSUE THREAD

**Issue by sdurrheimer** [DjLeChuck/foundryvtt-knight-compendium#22]
Il semblerait que Zakarik ait fait un correctif en rapport à l'impossibilité d'ajouter des améliorations sur le Longbow de l'armure Ranger: https://github.com/Zakarik/foundry-knight/releases/tag/v2.0.9

On voit bien le bouton "Modifier les améliorations" sur la fiche du Compendium (même si cliquer dessus ne fait rien):

![Screenshot 2023-01-31 at 13 32 41](https://user-images.githubusercontent.com/1931038/215761321-c3305e46-c997-4a79-9a57-202e9f973265.png)

Mais lorsque l'armure est affecté à une fiche de PJ, on peut rien faire:

![Screenshot 2023-01-31 at 13 38 13](https://user-images.githubusercontent.com/1931038/215762101-e954f923-44e0-4569-b8dc-e7901fa0ce64.png)

Est-ce qu'il aurait quelque chose à corriger ici comme l'aurait souligner Zakarik sur le discord "La Fonderie"?

![image](https://user-images.githubusercontent.com/1931038/215761902-fa5d799b-d270-409f-a3b2-5f6bb8a20b1b.png)

**Comment by DjLeChuck** [comment]
Corrigé par la `0.0.18` :)

**Comment by DjLeChuck** [comment]
Par contre, pour information, le bouton de modification ne sera pas visible sur la fiche du Chevalier directement.
Il faudra aller sur la fiche d'édition de la méta-armure en cliquant sur l'icône d'édition à côté de son nom un peu plus haut sur la fiche Chevalier (c'est le système qui est fait comme ça, ce n'est pas dépendant de ce module). 👍🏻
