### ISSUE TITLE
Erreurs sur la Monk

### ISSUE THREAD

**Issue by Zakarik** [DjLeChuck/foundryvtt-knight-compendium#25]
Petite erreur sur l'évolution de la Monk.

A 150PG, le Rayon d'énergie a 8D6 / 6D6, au lieu de 6D6 / 4D6.
A 250PG, le Rayon d'énergie a 6D6 / 4D6, au lieu de 8D6 / 6D6.

**Comment by DjLeChuck** [comment]
Oups, l’inversion bête. 😄 

Corrigé pour la prochaine version via 4ce914e135f2e28361a7c582530b27e73a7bb59a
