### ISSUE TITLE
Armure Warmaster : Modification du nombre d'implusions

### ISSUE THREAD

**Issue by Zakarik** [DjLeChuck/foundryvtt-knight-compendium#26]
Je transmet une issue qui m'est parvenue :

"Bonjour,

Il faut modifier la valeur du nombre d'impulsions de l'armure Warmaster dans l'évolution à 250PG pour mettre 5 impulsions."

**Comment by DjLeChuck** [comment]
Corrigé via 8f22d86d1fb0cb90e7f1b4a015332fe3a9126ef3

Publié dans la `10.0.2`

/close
