### ISSUE TITLE
Méta-armure Wizard - Mode Oriflame - Manque de Spécial

### ISSUE THREAD

**Issue by Phaerim** [DjLeChuck/foundryvtt-knight-compendium#29]
Salut,
Il manque actuellement au mode oriflame ses caractèristiques spéciales :
Anti-anathèmre
Lumière 2
"Affecte uniquement les créatures de l'anathème"

**Comment by DjLeChuck** [comment]
Zakarik,

Les effets sont bien dans l’armure dans le compendium, mais ils n’apparaissent pas une fois sur la fiche cf. screenshot (fiche à gauche, compendium à droite).

![image](https://github.com/DjLeChuck/foundryvtt-knight-compendium/assets/696780/b32d3337-58f0-4c29-997a-e8533514e215)

**Comment by DjLeChuck** [comment]
Cela venait du système, pas des compendiums, et a été corrigé.
