### ISSUE TITLE
Méta-armure Monk - Mode Zen - Echec des jets

### ISSUE THREAD

**Issue by Phaerim** [DjLeChuck/foundryvtt-knight-compendium#30]
Salut,
Souci peut être lié au système.
En activant le mode Zen et en faisant Plus que 5 succès le Jeu indique un échec.
![image](https://user-images.githubusercontent.com/15880906/233835605-d0f4d59a-41d7-4b1c-8210-5a91467dc682.png)

**Comment by DjLeChuck** [comment]
Cela venait du système, pas des compendiums, et a été corrigé.
