### ISSUE TITLE
PNJ Manquants

### ISSUE THREAD

**Issue by Lyraelle** [DjLeChuck/foundryvtt-knight-compendium#31]
Bonjour, bonsoir,

Il reste des PNJ officiels dans le livre de base.
Ces derniers sont dans les différents cadres d'aventure.

Cadre de l'Arche de Londres (p254 à 258)
- Hans Blechen

Cadre de l'Arche de Tokyo-Kyoto (p259 à 264)
- Mister Takeshi
- Hattori Masashige
- Ninja d'Hattori
- Oni Toshiro
- Hommes de main d'Oni

Cadre de la Sibérie Centrale (p269 à 271)
- Le Colosse
- Stasya Macharine
- Milan
- Alexandre Moreau
- Pillards de la Horde des Steppes

Cadre de Paris (p273 à 277)
- Pierre Langlois
- Théo de Sousa
- Adèle Girard
- Le Roi de Lafayette

Cadre de la Forêt-Noire (p278 à 281)
- Reisende
- La Princesse de la Forêt-Noire
- Ma, l'enfant sauvage
- Le Baron Stein
- Cohorte du Baron Stein
- Laex "Clover" McLucky

Cadre d'Istanbul (p282 à 285)
- Selim Xaba
- Mohamed Abdi
- Cevat Polat
- Yalim Polat
- Bernadette Bell
- Keyah Dixon
- Gardiens de la Caravane

Cadre de Rio de Janeiro (p291 à 294)
- Les Desesperados

Cadre de l'Arche de LASF (p299 à 301)
- John Scorluberg
- Bob Thompson
- Austin Cox

Cadre de Nashville (p302 à 305)
- Taylor Quick
- Hiro Zhang
- Jarod Bentley
- L'IA

Merci d'avance !

**Comment by DjLeChuck** [comment]
Fait pour la prochaine version
