### ISSUE TITLE
Mise à jour du système V3.11

### ISSUE THREAD

**Issue by Zakarik** [DjLeChuck/foundryvtt-knight-compendium#32]
Coucou !

Suite à la dernière mise à jour, il y a un petit changement sur la sorcerer.

Elle gagne un spécial "Énergie déficiente", qui lui rajoute les actions de ponctionner l'énergie de ses alliés.

Voilà.

Il me semble aussi que les valeurs ne sont pas corrects pour les évolutions de la Phase de la sorcerer (en passant de Niv. 1 à Niv. 2, ça coûte 8PE au lieu de 5PE).

Voilà, voilà.

Ah oui, pour les armures, je fais une migration du template des armures pour éviter les bugs, qui rajoute justement le spécial énergie déficiente dans ceux étant sélectionnable, ça n'a pas l'air de faire bug les armures déjà créées du compendium et je ne sais pas comment tu gères dans ce cas-là, mais je te préviens.

**Comment by DjLeChuck** [comment]
Corrigé avec la `10.0.4`.
