### ISSUE TITLE
Blessures graves ne donnent pas forcément les bons malus

### ISSUE THREAD

**Issue by Evalflower** [DjLeChuck/foundryvtt-knight-compendium#33]
Bonjour,

J'ai vérifié la totalité des blessures de la table des blessures graves et une seule ne correspond pas.
Il s'agit de la blessure "Oreilles éclatées" : Le personnage reçoit un malus de 1 à ses caractéristiques Perception, Déplacement et Instinct.

Il se trouve que le malus de Déplacement n'est pas entré.

**Comment by DjLeChuck** [comment]
Ajouté via la `10.1.0` 👍🏻
