### ISSUE TITLE
Méta-armures de légendes et capacités ultime

### ISSUE THREAD

**Issue by Kyrantox** [DjLeChuck/foundryvtt-knight-compendium#38]
Bonjour DjLeChuck,

Je souhaite tout d'abord vous remercier pour tout le travail fournit sur ce compendium 😄 .
Je ne sais pas si le sujet à déjà été abordé mais les méta-armures de légendes et les capacités ultime ne sont pas présent dans la liste des items.
Désolé de vous rajouter du travail fastidieux ^^'.

Bon courage !

**Comment by DjLeChuck** [comment]
Fait dans la version 11.1.0
