### ISSUE TITLE
Erreur de Défense / Réaction pour certaines créatures (Spoiler inside)

### ISSUE THREAD

**Issue by Zakarik** [DjLeChuck/foundryvtt-knight-compendium#39]
Le Monstre Machine, le Construct et le Ravageur ont une erreur dans leurs valeurs de réaction et de défense.

C'est dû au fait que la Machine exceptionnelle donne des bonus. Il faut juste baisser leur base pour que le total soit égal à leur valeur du bestiaire. J'ai vérifié les autres créatures de la machine et les valeurs sont correctes.

**Comment by DjLeChuck** [comment]
Fait dans la version 11.1.0
