### ISSUE TITLE
Erreurs

### ISSUE THREAD

**Issue by Zakarik** [DjLeChuck/foundryvtt-knight-compendium#4]
La Druid a une évolution d'armure programmée... Alors que faut pas, parce que c'est spécial.
La Ranger n'a pas le bouton "Les évolutions d'armures sont à acheter" sélectionné.

**Comment by Zakarik** [comment]
L'inconvénient "Trop prudent" n'est pas paramétré pour retirer 1D en initiative.

**Comment by Zakarik** [comment]
L'attaque sur casque devrait être réglée en "Permanent", vu qu'elle ne nécessite pas d'activation particulière.

**Comment by Sphins** [comment]
les remarques sont prises en comte restera a faire la mise a jours dans le compendium
