### ISSUE TITLE
Bug du Canon Balder

### ISSUE THREAD

**Issue by Zakarik** [DjLeChuck/foundryvtt-knight-compendium#7]
- Les dégâts ne sont pas variables, alors qu'ils devraient l'être.
- La violence n'est pas variable, alors qu'elle devrait l'être.
- Il faut mettre en place le coût d'augmentation de ces valeurs (possible maintenant).
- On peut retirer l'effet "Overclocke" qui n'est pas un vrai effet, juste pour le Knight JDR Système, pour représenter les augmentations de dégâts / violence possible.

**Comment by DjLeChuck** [comment]
Corrigé pour la prochaine version.
