### ISSUE TITLE
Crash de la Ranger

### ISSUE THREAD

**Issue by Zakarik** [DjLeChuck/foundryvtt-knight-compendium#9]
J'ai rajouté la possibilité de mettre des améliorations d'armes à distance sur le longbow, sauf que ça fait qu'il manque 
distance : {
  raw:[],
  custom:[]
}

Sans ça, ça fait crash la fiche de l'armure et du personnage qui la porte.

**Comment by DjLeChuck** [comment]
Corrigé sur la prochaine version.
